INSERT INTO glossary_terms (term, category, definition) VALUES 
-- BANKING
('Balance Transfer', 'Banking', 'Transferring credit card debt to another card with a lower interest rate.'),
('Cash Reserve Ratio (CRR)', 'Banking', 'Share of net demand and time liabilities that banks must maintain with RBI.'),
('Compound Interest', 'Banking', 'Interest calculated on the initial principal and also on the accumulated interest of previous periods.'),
('Current Account', 'Banking', 'A bank account for businesses with no limit on the number of transactions per day.'),
('Base Rate', 'Banking', 'The minimum interest rate of a bank below which it cannot lend, except in allowed cases.'),
('Fixed Deposit (FD)', 'Banking', 'A savings account where money is deposited for a fixed period at a fixed interest rate.'),
('IMPS (Immediate Payment Service)', 'Banking', 'An instant interbank electronic fund transfer service available 24x7.'),
('KYC (Know Your Customer)', 'Banking', 'Mandatory process of identifying and verifying the identity of the client.'),
('MCLR (Marginal Cost of Funds based Lending Rate)', 'Banking', 'The minimum interest rate of a bank below which it cannot lend, replacing the base rate system.'),
('NEFT (National Electronic Funds Transfer)', 'Banking', 'A nationwide payment system facilitating one-to-one funds transfer.'),
('Net Banking', 'Banking', 'Online banking service provided by banks for conducting financial transactions.'),
('Overdraft', 'Banking', 'A credit facility allowing accountholders to withdraw more money than is available in their account.'),
('Recurring Deposit (RD)', 'Banking', 'A deposit plan allowing individuals to deposit a fixed amount every month for a fixed tenure.'),
('RTGS (Real Time Gross Settlement)', 'Banking', 'A fund transfer system where transfer of money takes place from one bank to another on a real-time basis.'),
('Savings Account', 'Banking', 'A deposit account providing principal security and a modest interest rate.'),
('UPI (Unified Payments Interface)', 'Banking', 'A system that powers multiple bank accounts into a single mobile application for seamless fund routing.'),
('Zero Balance Account', 'Banking', 'A savings account that does not require maintained minimum balance.'),

-- LENDING / LOANS
('Amortization', 'Loans', 'The process of spreading out a loan into a series of fixed payments over time.'),
('Collateral', 'Loans', 'Something pledged as security for repayment of a loan, to be forfeited in the event of a default.'),
('Credit Appraisal', 'Loans', 'The process by which a lender determines the ability of a borrower to repay a loan.'),
('Debt-to-Income Ratio (DTI)', 'Loans', 'Percentage of gross monthly income that goes towards paying debts.'),
('Down Payment', 'Loans', 'Initial up-front partial payment for the purchase of extensive items like a house or car.'),
('EMI (Equated Monthly Installment)', 'Loans', 'A fixed payment amount made by a borrower to a lender at a specified date each calendar month.'),
('Floating Interest Rate', 'Loans', 'An interest rate that changes periodically based on market conditions/RBI rates.'),
('Foreclosure', 'Loans', 'Legal process where a lender attempts to recover the balance of a loan from a borrower who has stopped making payments.'),
('Loan Against Property (LAP)', 'Loans', 'A secured loan availed against a commercial or residential property.'),
('Loan Tenure', 'Loans', 'The duration for which the loan amount is sanctioned.'),
('Moratorium Period', 'Loans', 'A time during the loan term when the borrower is not required to make any repayment.'),
('Part Prepayment', 'Loans', 'Paying a portion of the outstanding loan amount before the due date to reduce the principal or tenure.'),
('Personal Loan', 'Loans', 'An unsecured loan taken by individuals to meet personal expenses.'),
('Principal', 'Loans', 'The original sum of money borrowed in a loan or put into an investment.'),
('Processing Fee', 'Loans', 'A one-time charge by the lender for processing the loan application.'),
('Secured Loan', 'Loans', 'A loan backed by collateral such as a house, car, or gold.'),
('Top-up Loan', 'Loans', 'An additional loan amount provided by the lender on an existing loan.'),
('Unsecured Loan', 'Loans', 'A loan that is issued and supported only by the borrower''s creditworthiness, without collateral.'),

-- INSURANCE
('Add-on Covers', 'Insurance', 'Additional benefits that can be purchased to enhance the coverage of a base insurance policy.'),
('Claim Settlement Ratio (CSR)', 'Insurance', 'The percentage of claims settled by an insurer out of the total claims received.'),
('Co-payment', 'Insurance', 'A clause where the policyholder agrees to pay a percentage of the claim amount.'),
('Comprehensive Insurance', 'Insurance', 'A policy that covers third-party liability as well as own damage to the vehicle.'),
('Critical Illness Cover', 'Insurance', 'Insurance coverage for specific life-threatening diseases often listed in the policy.'),
('Deductible', 'Insurance', 'The amount you pay for covered health care services before your insurance plan starts to pay.'),
('Endowment Plan', 'Insurance', 'A life insurance policy combining coverage and savings.'),
('Grace Period', 'Insurance', 'Extra time given after the premium due date to pay the premium without policy lapsing.'),
('Health Insurance', 'Insurance', 'Insurance that covers the whole or a part of the risk of a person incurring medical expenses.'),
('IDV (Insured Declared Value)', 'Insurance', 'The maximum sum assured fixed by the insurer for a vehicle insurance policy.'),
('Life Insurance', 'Insurance', 'A contract where the insurer promises to pay a designated beneficiary a sum of money upon the death of an insured person.'),
('Maturity Benefit', 'Insurance', 'The lump sum amount paid by the insurance company when the policy matures.'),
('No Claim Bonus (NCB)', 'Insurance', 'A discount on premium given for every claim-free year.'),
('Nominee', 'Insurance', 'The person appointed by the policyholder to receive the benefits in case of the policyholder''s death.'),
('Policy Lapse', 'Insurance', 'Termination of insurance coverage due to non-payment of premiums.'),
('Premium', 'Insurance', 'The amount to be paid for a contract of insurance.'),
('Surrender Value', 'Insurance', 'The amount the policyholder will get from the insurance company if they decide to exit the policy before maturity.'),
('Term Insurance', 'Insurance', 'Pure life insurance that provides coverage for a defined period of time.'),
('Third Party Liability', 'Insurance', 'Coverage for damages caused to a third person or their property by your vehicle.'),
('ULIP (Unit Linked Insurance Plan)', 'Insurance', 'A product that offers a mix of insurance and investment.'),
('Waiting Period', 'Insurance', 'The time span during which specific policy benefits typically do not apply.'),

-- MUTUAL FUNDS & INVESTING
('Active Fund Management', 'Mutual Funds', 'A strategy where fund managers actively buy and sell securities to outperform a benchmark.'),
('Alpha', 'Investing', 'A measure of the active return on an investment, the performance of that investment compared with a suitable market index.'),
('Asset Allocation', 'Investing', 'An investment strategy that aims to balance risk and reward by apportioning a portfolio''s assets according to an individual''s goals.'),
('Bear Market', 'Investing', 'A market condition in which the prices of securities are falling or are expected to fall.'),
('Benchmark', 'Mutual Funds', 'A standard against which the performance of a mutual fund is measured.'),
('Beta', 'Investing', 'A measure of the volatility, or systematic risk, of a security or portfolio in comparison to the market as a whole.'),
('Blue Chip Stocks', 'Investing', 'Stocks of huge, well-established, and financially sound companies with a history of reliable performance.'),
('Bull Market', 'Investing', 'A market condition in which prices are rising or are expected to rise.'),
('CAGR (Compound Annual Growth Rate)', 'Investing', 'The rate of return that would be required for an investment to grow from its beginning balance to its ending balance, assuming the profits were reinvested.'),
('Debt Fund', 'Mutual Funds', 'A mutual fund that invests in fixed-income securities like bonds and treasury bills.'),
('Diversification', 'Investing', 'A risk management strategy that mixes a wide variety of investments within a portfolio.'),
('Dividend Yield', 'Investing', 'A financial ratio that shows how much a company pays out in dividends each year relative to its stock price.'),
('ELSS (Equity Linked Savings Scheme)', 'Mutual Funds', 'A type of diversified equity mutual fund which is tax saving under section 80C.'),
('Equity Fund', 'Mutual Funds', 'A mutual fund that invests principally in stocks.'),
('ETF (Exchange Traded Fund)', 'Investing', 'An investment fund traded on stock exchanges, tailored to track specific indexes.'),
('Exit Load', 'Mutual Funds', 'A fee charged if you redeem your mutual fund units before a specific period (usually 1 year).'),
('Expense Ratio', 'Mutual Funds', 'The annual fee charged by a mutual fund scheme to manage your money.'),
('Growth Stock', 'Investing', 'A share in a company whose earnings are expected to grow at an above-average rate relative to the market.'),
('Index Fund', 'Mutual Funds', 'A mutual fund constructed to match or track the components of a financial market index.'),
('Large Cap', 'Investing', 'Companies with a large market capitalization, usually stable and well-established.'),
('Lump Sum', 'Investing', 'A single complete sum of money invested at one time.'),
('Market Capitalization', 'Investing', 'The total value of a company''s outstanding shares of stock.'),
('Mid Cap', 'Investing', 'Companies with a market capitalization between large and small cap companies.'),
('NAV (Net Asset Value)', 'Mutual Funds', 'The market value of a single unit of a mutual fund scheme.'),
('Nifty 50', 'Investing', 'A benchmark Indian stock market index that represents the weighted average of 50 of the largest Indian companies listed on the NSE.'),
('P/E Ratio (Price-to-Earnings)', 'Investing', 'The ratio for valuing a company that measures its current share price relative to its per-share earnings.'),
('Portfolio', 'Investing', 'A collection of financial investments like stocks, bonds, commodities, cash, and cash equivalents.'),
('Sensex', 'Investing', 'The benchmark index of the Bombay Stock Exchange (BSE).'),
('SIP (Systematic Investment Plan)', 'Investing', 'A method of investing a fixed sum regularly in a mutual fund scheme.'),
('Small Cap', 'Investing', 'Public companies with a relatively small market capitalization.'),
('Volatility', 'Investing', 'Liability to change rapidly and unpredictably, especially for the worse.'),

-- CREDIT CARDS
('Annual Fee', 'Credit Cards', 'A yearly fee charged by credit card companies for the privilege of using their card.'),
('APR (Annual Percentage Rate)', 'Credit Cards', 'The yearly interest rate you''ll be charged for borrowing money, including fees.'),
('Balance Transfer', 'Credit Cards', 'Moving the debt from one credit card to another, usually to take advantage of a lower interest rate.'),
('Cash Advance', 'Credit Cards', 'A service provided by credit card issuers allowing cardholders to withdraw cash.'),
('Chargeback', 'Credit Cards', 'A demand by a credit-card provider for a retailer to make good the loss on a fraudulent or disputed transaction.'),
('Credit Limit', 'Credit Cards', 'The maximum amount of credit a financial institution extends to a client.'),
('Credit Score', 'Credit Cards', 'A numerical expression based on a level analysis of a person''s credit files, to represent the creditworthiness of an individual.'),
('Grace Period', 'Credit Cards', 'The time during which you are allowed to pay your credit card bill without having to pay interest.'),
('Minimum Due', 'Credit Cards', 'The smallest amount of a credit card bill that a consumer must pay to remain in good standing.'),
('Reward Points', 'Credit Cards', 'Incentives offered by credit card issuers to encourage use of the card.'),
('Secured Credit Card', 'Credit Cards', 'A credit card backed by a cash deposit from the cardholder.'),

-- ECONOMY & TAXATION
('Capital Gains Tax', 'Taxation', 'Tax levied on profit from the sale of property or an investment.'),
('Direct Tax', 'Taxation', 'A tax, such as income tax, that is levied on the income or profits of the person who pays it.'),
('Fiscal Deficit', 'Economy', 'The difference between total revenue and total expenditure of the government.'),
('GDP (Gross Domestic Product)', 'Economy', 'The total value of goods produced and services provided in a country during one year.'),
('GST (Goods and Services Tax)', 'Taxation', 'An indirect tax used in India on the supply of goods and services.'),
('Income Tax Slabs', 'Taxation', 'Different tax rates are charged for different ranges of income.'),
('Indirect Tax', 'Taxation', 'A tax levied on goods and services rather than on income or profits.'),
('Inflation', 'Economy', 'A general increase in prices and fall in the purchasing power of money.'),
('Repo Rate', 'Economy', 'The rate at which the RBI lends money to commercial banks.'),
('Reverse Repo Rate', 'Economy', 'The rate at which the RBI borrows money from commercial banks.'),
('TDS (Tax Deducted at Source)', 'Taxation', 'A means of collecting income tax in India, under the Income Tax Act of 1961.');
ON CONFLICT DO NOTHING;
