/**
 * File Generators
 * Generates Excel, PDF, CSV files from templates
 */

import { DashboardTemplate } from './dashboard-templates';

/**
 * Generate Excel file from template (CSV format for now)
 * TODO: Install ExcelJS for real .xlsx files
 */
export function generateExcelFromTemplate(template: DashboardTemplate): string {
    const lines: string[] = [];
    
    // Add headers
    const headers = template.columns.map(col => col.name);
    lines.push(headers.join(','));
    
    // Add sample data if available
    if (template.sampleData && template.sampleData.length > 0) {
        template.sampleData.forEach(row => {
            const formattedRow = row.map((cell: any) => {
                // Escape commas and quotes in CSV
                const cellStr = String(cell);
                if (cellStr.includes(',') || cellStr.includes('"') || cellStr.includes('\n')) {
                    return `"${cellStr.replace(/"/g, '""')}"`;
                }
                return cellStr;
            });
            lines.push(formattedRow.join(','));
        });
    }
    
    // Add formulas as comments (Excel will need manual setup)
    if (template.formulas && template.formulas.length > 0) {
        lines.push('');
        lines.push('Formulas:');
        template.formulas.forEach(formula => {
            lines.push(`Cell ${formula.cell}: ${formula.formula} - ${formula.description}`);
        });
    }
    
    return lines.join('\n');
}

/**
 * Generate PDF content from template
 * Returns HTML that can be converted to PDF
 */
export function generatePDFFromTemplate(template: DashboardTemplate): string {
    const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${template.name}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 40px;
            color: #333;
        }
        h1 {
            color: #0d9488;
            border-bottom: 3px solid #0d9488;
            padding-bottom: 10px;
        }
        h2 {
            color: #64748b;
            margin-top: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #e2e8f0;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f1f5f9;
            font-weight: bold;
        }
        .description {
            color: #64748b;
            margin: 20px 0;
            line-height: 1.6;
        }
        .formula {
            background-color: #f8fafc;
            padding: 10px;
            margin: 10px 0;
            border-left: 3px solid #0d9488;
        }
    </style>
</head>
<body>
    <h1>${template.name}</h1>
    <p class="description">${template.description}</p>
    
    <h2>Instructions</h2>
    <p>This template helps you track your ${template.category} finances. Follow these steps:</p>
    <ol>
        <li>Open this file in Excel, Google Sheets, or Notion</li>
        <li>Replace sample data with your own information</li>
        <li>Formulas will automatically calculate values</li>
        <li>Update regularly to track your progress</li>
    </ol>
    
    <h2>Columns</h2>
    <table>
        <thead>
            <tr>
                <th>Column Name</th>
                <th>Type</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            ${template.columns.map(col => `
                <tr>
                    <td><strong>${col.name}</strong></td>
                    <td>${col.type}</td>
                    <td>${col.width ? `Width: ${col.width}` : 'Auto'}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
    
    ${template.formulas && template.formulas.length > 0 ? `
    <h2>Formulas</h2>
    ${template.formulas.map(formula => `
        <div class="formula">
            <strong>Cell ${formula.cell}:</strong> ${formula.formula}<br>
            <em>${formula.description}</em>
        </div>
    `).join('')}
    ` : ''}
    
    <h2>Sample Data</h2>
    <table>
        <thead>
            <tr>
                ${template.columns.map(col => `<th>${col.name}</th>`).join('')}
            </tr>
        </thead>
        <tbody>
            ${template.sampleData && template.sampleData.length > 0 ? template.sampleData.map(row => `
                <tr>
                    ${row.map((cell: any) => `<td>${cell}</td>`).join('')}
                </tr>
            `).join('') : '<tr><td colspan="' + template.columns.length + '">No sample data</td></tr>'}
        </tbody>
    </table>
    
    <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; color: #64748b; font-size: 12px;">
        <p>Generated by InvestingPro.in - Your Smart Financial Companion</p>
        <p>Visit <a href="https://investingpro.in">investingpro.in</a> for more financial tools and resources</p>
    </div>
</body>
</html>
    `;
    
    return html;
}

/**
 * Generate CSV file
 */
export function generateCSVFromTemplate(template: DashboardTemplate): string {
    return generateExcelFromTemplate(template); // CSV and Excel (CSV format) are the same
}

/**
 * Generate Notion import instructions
 */
export function generateNotionInstructions(template: DashboardTemplate): string {
    return `
# ${template.name} - Notion Setup Guide

## Step 1: Create a New Database
1. In Notion, create a new database (Table view)
2. Name it: "${template.name}"

## Step 2: Add Columns
Add these columns to your Notion database:

${template.columns.map((col, index) => `
${index + 1}. **${col.name}**
   - Type: ${mapColumnTypeToNotion(col.type)}
   - ${col.description || 'No description'}
`).join('')}

## Step 3: Import Sample Data
1. Copy the sample data below
2. Paste into your Notion database
3. Adjust formulas as needed (Notion uses different formula syntax)

## Sample Data Structure
${template.columns.map(col => col.name).join(' | ')}
${template.columns.map(() => '---').join(' | ')}
${template.sampleData && template.sampleData.length > 0 ? template.sampleData.map(row => row.join(' | ')).join('\n') : 'No sample data'}

## Formulas (Convert to Notion Syntax)
${template.formulas ? template.formulas.map(f => `- ${f.cell}: ${f.formula} - ${f.description}`).join('\n') : 'No formulas'}

## Tips
- Notion formulas use different syntax than Excel
- Use Notion's formula editor to convert Excel formulas
- You can import CSV data directly into Notion
- Use Notion's templates feature to save this as a template

---
Generated by InvestingPro.in
    `.trim();
}

function mapColumnTypeToNotion(excelType: string): string {
    const mapping: Record<string, string> = {
        'text': 'Text',
        'number': 'Number',
        'date': 'Date',
        'currency': 'Number (with currency format)',
        'percentage': 'Number (with percentage format)',
        'formula': 'Formula'
    };
    return mapping[excelType] || 'Text';
}
