"use client";

import React, { useState } from 'react';
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, PenTool, Save, RotateCcw, CheckCircle, AlertCircle, Sparkles, Zap, Twitter, Share2 } from "lucide-react";
import { articleService } from '@/lib/cms/article-service';
import { useRouter } from 'next/navigation';
import { GeneratedArticle } from '@/lib/ai/article-writer';
import AdminLayout from "@/components/admin/AdminLayout";
import SocialDistributionPanel from "@/components/admin/SocialDistributionPanel";
import AIHealthMonitor from "@/components/admin/AIHealthMonitor";
import { toast } from 'sonner';

interface SocialPosts {
    twitter?: string[];
    linkedin?: string;
    instagram?: string;
    generated_at?: string;
}

export default function ContentFactoryPage() {
    const router = useRouter();
    
    // Input State
    const [topic, setTopic] = useState('');
    const [keywords, setKeywords] = useState('');
    const [tone, setTone] = useState('educational');

    // Process State
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedArticle, setGeneratedArticle] = useState<GeneratedArticle | null>(null);
    const [isPublishing, setIsPublishing] = useState(false);
    const [error, setError] = useState<string | null>(null);
    
    // Social Posts State
    const [socialPosts, setSocialPosts] = useState<SocialPosts | null>(null);
    const [isGeneratingSocial, setIsGeneratingSocial] = useState(false);

    const handleGenerate = async () => {
        if (!topic) return;
        
        setIsGenerating(true);
        setError(null);
        setGeneratedArticle(null);
        setSocialPosts(null);

        try {
            const keywordList = keywords.split(',').map(k => k.trim()).filter(Boolean);
            
            const generatePromise = fetch('/api/admin/generate-article', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ topic, keywords: keywordList, tone })
            }).then(async (response) => {
                if (!response.ok) {
                    const data = await response.json().catch(() => ({}));
                    throw new Error(data.error || data.details || 'Generation failed');
                }
                const data = await response.json();
                setGeneratedArticle(data);
                return data;
            });

            toast.promise(generatePromise, {
                loading: 'Initializing AI Writer...',
                success: 'Content Generated Successfully',
                error: (err: Error) => `Generation failed: ${err.message}`
            });

            await generatePromise;
        } catch (err: any) {
            setError(err.message || 'Failed to generate article. AI might be busy or token limit reached.');
            console.error(err);
        } finally {
            setIsGenerating(false);
        }
    };

    const handlePublish = async (status: 'draft' | 'published') => {
        if (!generatedArticle) return;
        
        setIsPublishing(true);
        try {
            const slug = generatedArticle.title
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/(^-|-$)/g, '');

            const result = await articleService.createArticle(
                {
                    body_markdown: generatedArticle.content,
                    body_html: '', // Will be generated by service
                },
                {
                    title: generatedArticle.title,
                    slug: slug,
                    excerpt: generatedArticle.excerpt,
                    category: 'investing-basics', // Default, should be selectable
                    tags: generatedArticle.tags,
                    seo_title: generatedArticle.seo_title,
                    seo_description: generatedArticle.seo_description,
                    ai_generated: true,
                    ai_metadata: generatedArticle.ai_metadata
                }
            );

            if (status === 'published') {
                await articleService.publishArticle(
                    result.id, 
                    { body_markdown: generatedArticle.content, body_html: '' }, 
                    {} // No extra metadata updates needed
                );
            }

            toast.success('Article Saved! Redirecting to Editor...');
            router.push(`/admin/articles/${result.id}/edit`);
        } catch (err) {
            toast.error('Failed to save article.');
            setError('Failed to save article.');
            console.error(err);
        } finally {
            setIsPublishing(false);
        }
    };

    const handleGenerateSocial = async () => {
        if (!generatedArticle) return;
        
        setIsGeneratingSocial(true);
        try {
            const response = await fetch('/api/admin/generate-social', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    articleId: 'preview', // Placeholder for unsaved article
                    title: generatedArticle.title,
                    content: generatedArticle.content
                })
            });
            
            if (!response.ok) throw new Error('Failed to generate social posts');
            
            const data = await response.json();
            setSocialPosts(data.posts);
            toast.success('Social posts generated!');
        } catch (err) {
            toast.error('Failed to generate social posts');
            console.error(err);
        } finally {
            setIsGeneratingSocial(false);
        }
    };

    return (
        <AdminLayout>
            <div className="p-8 max-w-[1600px] mx-auto w-full">
                <div className="mb-10 border-b border-white/5 pb-8">
                    <div className="flex items-center justify-between">
                        <div>
                            <h1 className="text-3xl font-extrabold text-white tracking-tight flex items-center gap-4">
                                <div className="w-12 h-12 rounded-xl bg-indigo-500/10 flex items-center justify-center shadow-[0_0_20px_rgba(99,102,241,0.15)]">
                                    <Sparkles className="w-6 h-6 text-indigo-400" />
                                </div>
                                Content Factory
                                <Badge className="bg-indigo-500/10 text-indigo-400 border-indigo-500/20 ml-2 font-bold tracking-wider">BETA</Badge>
                            </h1>
                            <p className="text-slate-400 mt-3 ml-16 font-medium tracking-wide max-w-2xl">
                                Advanced autonomous content generation workspace using Alpha Intelligence.
                            </p>
                        </div>
                        <AIHealthMonitor />
                    </div>
                </div>

                <div className="grid lg:grid-cols-12 gap-8 h-[calc(100vh-250px)]">
                    {/* Left Panel: Controls */}
                    <div className="lg:col-span-4 space-y-6 h-full flex flex-col">
                        <Card className="bg-white/[0.03] border-white/5 rounded-2xl flex-1 flex flex-col">
                            <CardHeader className="border-b border-white/5 px-6 py-5">
                                <CardTitle className="text-sm font-bold uppercase tracking-widest text-slate-400 flex items-center gap-2">
                                    <PenTool className="w-4 h-4" />
                                    Configuration Vectors
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-6 space-y-6 flex-1">
                                <div className="space-y-4">
                                    <div className="space-y-2">
                                        <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                                            Topic / Title Idea
                                        </label>
                                        <Input 
                                            placeholder="e.g. Benefits of SIP vs Lumpsum" 
                                            value={topic}
                                            onChange={(e) => setTopic(e.target.value)}
                                            className="bg-black/20 border-white/10 text-white h-12 text-lg focus:border-indigo-500/50 focus:ring-indigo-500/20"
                                        />
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                                            Keywords (Directives)
                                        </label>
                                        <Input 
                                            placeholder="mutual funds, investing, wealth creation" 
                                            value={keywords}
                                            onChange={(e) => setKeywords(e.target.value)}
                                            className="bg-black/20 border-white/10 text-slate-200 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                                        />
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                                            Narrative Tone
                                        </label>
                                        <select 
                                            className="w-full h-11 px-3 rounded-lg border border-white/10 bg-black/20 text-slate-200 text-sm focus:outline-none focus:border-indigo-500/50 focus:ring-1 focus:ring-indigo-500/20 transition-all appearance-none"
                                            value={tone}
                                            onChange={(e) => setTone(e.target.value)}
                                        >
                                            <option value="educational">Educational (Beginner Friendly)</option>
                                            <option value="professional">Professional (Expert Analysis)</option>
                                            <option value="news">News style (Fact based)</option>
                                        </select>
                                    </div>

                                    <div className="pt-4">
                                        <Button 
                                            onClick={handleGenerate} 
                                            disabled={!topic || isGenerating}
                                            className="w-full h-14 text-base font-bold uppercase tracking-widest bg-indigo-600 hover:bg-indigo-700 shadow-[0_0_20px_rgba(99,102,241,0.3)] border-0 transition-all active:scale-95"
                                        >
                                            {isGenerating ? (
                                                <>
                                                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                                    Synthesizing...
                                                </>
                                            ) : (
                                                <>
                                                    <Zap className="mr-2 h-5 w-5 fill-current" />
                                                    Generate Content
                                                </>
                                            )}
                                        </Button>
                                    </div>

                                    {error && (
                                        <div className="p-4 bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-xl flex items-start gap-3 text-sm">
                                            <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                                            {error}
                                        </div>
                                    )}
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Right Panel: Preview */}
                    <div className="lg:col-span-8 space-y-6 h-full flex flex-col">
                        {generatedArticle ? (
                            <Card className="bg-white/[0.03] border-white/5 rounded-2xl flex-1 flex flex-col overflow-hidden h-full">
                                <CardHeader className="border-b border-white/5 px-6 py-4 flex flex-row items-center justify-between bg-white/[0.01]">
                                    <div className="flex items-center gap-3">
                                        <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center">
                                            <CheckCircle className="w-4 h-4 text-emerald-400" />
                                        </div>
                                        <CardTitle className="text-sm font-bold uppercase tracking-widest text-emerald-400">
                                            Output Verified
                                        </CardTitle>
                                    </div>
                                    <div className="flex gap-3">
                                        <Button 
                                            variant="ghost" 
                                            size="sm"
                                            onClick={handleGenerate}
                                            disabled={isPublishing}
                                            className="text-slate-400 hover:text-white hover:bg-white/5"
                                        >
                                            <RotateCcw className="w-4 h-4 mr-2" />
                                            Regenerate
                                        </Button>
                                        <Button 
                                            size="sm"
                                            onClick={() => handlePublish('published')}
                                            disabled={isPublishing}
                                            className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold border-0 shadow-[0_0_15px_rgba(16,185,129,0.3)]"
                                        >
                                            {isPublishing ? (
                                                <Loader2 className="w-4 h-4 animate-spin" />
                                            ) : (
                                                <>
                                                    <Save className="w-4 h-4 mr-2" />
                                                    Push to CMS
                                                </>
                                            )}
                                        </Button>
                                    </div>
                                </CardHeader>

                                <div className="flex-1 overflow-y-auto p-8 space-y-8 no-scrollbar bg-[#0f1115]">
                                    <div>
                                        <span className="text-[10px] uppercase font-bold text-slate-500 tracking-widest mb-2 block">Title Asset</span>
                                        <h3 className="text-2xl font-bold text-white leading-tight">{generatedArticle.title}</h3>
                                    </div>
                                    
                                    <div>
                                        <span className="text-[10px] uppercase font-bold text-slate-500 tracking-widest mb-2 block">Excerpt / Meta</span>
                                        <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-slate-300 italic text-sm border-l-4 border-l-indigo-500">
                                            {generatedArticle.excerpt}
                                        </div>
                                    </div>

                                    <div>
                                        <span className="text-[10px] uppercase font-bold text-slate-500 tracking-widest mb-4 block">Markdown Preview</span>
                                        <div className="prose prose-invert prose-sm max-w-none text-slate-300">
                                            <pre className="whitespace-pre-wrap font-mono text-xs bg-black/30 p-6 rounded-xl border border-white/5 overflow-x-auto text-slate-400">
                                                {generatedArticle.content}
                                            </pre>
                                        </div>
                                    </div>

                                    <div className="pt-6 border-t border-white/5">
                                        <span className="text-[10px] uppercase font-bold text-slate-500 tracking-widest mb-3 block">Taxonomy Tags</span>
                                        <div className="flex flex-wrap gap-2">
                                            {generatedArticle.tags.map(tag => (
                                                <Badge key={tag} className="bg-white/5 text-slate-300 border border-white/10 hover:bg-white/10 px-3 py-1">#{tag}</Badge>
                                            ))}
                                        </div>
                                    </div>

                                    {/* Social Distribution Section */}
                                    <div className="pt-6 border-t border-white/5">
                                        <div className="flex items-center justify-between mb-4">
                                            <span className="text-[10px] uppercase font-bold text-slate-500 tracking-widest flex items-center gap-2">
                                                <Share2 className="w-4 h-4" />
                                                Social Distribution
                                            </span>
                                            {!socialPosts && (
                                                <Button
                                                    size="sm"
                                                    onClick={handleGenerateSocial}
                                                    disabled={isGeneratingSocial}
                                                    className="bg-pink-600 hover:bg-pink-700 text-white text-xs"
                                                >
                                                    {isGeneratingSocial ? (
                                                        <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                                                    ) : (
                                                        <Twitter className="w-3 h-3 mr-1" />
                                                    )}
                                                    Generate Posts
                                                </Button>
                                            )}
                                        </div>
                                        
                                        {socialPosts ? (
                                            <SocialDistributionPanel
                                                articleId="preview"
                                                articleTitle={generatedArticle.title}
                                                articleContent={generatedArticle.content}
                                                existingPosts={socialPosts}
                                                onRegenerate={handleGenerateSocial}
                                            />
                                        ) : (
                                            <div className="p-6 bg-white/[0.02] rounded-xl border border-dashed border-white/10 text-center">
                                                <p className="text-slate-500 text-sm">
                                                    Click "Generate Posts" to create Twitter threads, LinkedIn posts, and Instagram captions.
                                                </p>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </Card>
                        ) : (
                            <div className="bg-white/[0.01] border-2 border-dashed border-white/5 rounded-2xl h-full flex flex-col items-center justify-center text-slate-500 group">
                                <div className="w-20 h-20 rounded-full bg-indigo-500/5 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500 shadow-[0_0_40px_rgba(99,102,241,0.1)]">
                                    <Sparkles className="w-8 h-8 text-indigo-500/40" />
                                </div>
                                <h3 className="text-xl font-bold text-slate-400 mb-2">Awaiting Parameters</h3>
                                <p className="text-sm text-slate-600 font-medium tracking-wide max-w-xs text-center">
                                    Initialize the prompt vectors on the left to begin synthesis.
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </AdminLayout>
    );
}
