
import { api } from '@/lib/api';
import { logger } from '@/lib/logger';
import { 
    AIDataSource, 
    AIContentMetadata, 
    calculateConfidence, 
    createChangeLog, 
    ALLOWED_AI_OPERATIONS 
} from './constraints';
import { logAICost, calculateCostFromTokens } from './cost-tracker';

import { linkInjector } from '@/lib/services/link-injector';

export interface GeneratedArticle {
    title: string;
    content: string; // Markdown
    excerpt: string;
    seo_title: string;
    seo_description: string;
    tags: string[];
    ai_metadata: AIContentMetadata;
    // Cost tracking info (from AI provider)
    provider?: string;
    model?: string;
    usage?: {
        input_tokens: number;
        output_tokens: number;
        total_tokens: number;
    };
}

/**
 * Generate a full article using AI
 */
export interface GenerateArticleParams {
    topic: string;
    keywords: string[];
    tone?: string;
    targetAudience?: string;
    sourceContent?: string;
    sourceUrl?: string;
    articleId?: string; // Optional: for cost attribution after article creation
}

/**
 * Generate a full article using AI
 */
export async function generateArticle({
    topic,
    keywords,
    tone = 'educational',
    targetAudience = 'Indian Investors',
    sourceContent,
    sourceUrl,
    articleId
}: GenerateArticleParams): Promise<GeneratedArticle> {
    
    const groundingContext = sourceContent
        ? `\nGROUNDING MATERIAL (Primary Source):\n"""\n${sourceContent.substring(0, 8000)}\n"""\nINSTRUCTION: Base your analysis and facts primarily on the grounding material above. Cite it where appropriate.`
        : '';

    // Construct a specialized prompt for high-quality financial content
    const prompt = `You are an expert financial writer for InvestingPro.in, India's leading financial comparison platform.
    
    Task: Write a comprehensive, SEO-optimized article.
    
    Topic: ${topic}
    Keywords: ${keywords.join(', ')}
    Tone: ${tone}
    Target Audience: ${targetAudience}
    ${groundingContext}
    
    Requirements:
    1. Structure:
       - H1 Title (Catchy, Keyword-rich)
       - Introduction (Hook + Problem Statement)
       - Key Concepts / Main Body (Use H2, H3, Lists, Tables where appropriate)
       - Pros & Cons (if applicable)
       - Conclusion (Summary + Call to Action)
       - FAQs (3-5 questions)
    
    2. Formatting:
       - Use standard Markdown.
       - Use bolding for emphasis.
       - Use specific Indian context (₹ currency, Indian laws, Indian examples).
    
    3. Output Format:
       - Return a JSON object with the following fields:
         {
           "title": "The H1 Title",
           "content": "The full markdown content string (excluding title)",
           "excerpt": "A 2-sentence summary for the card preview",
           "seo_title": "Title tag (under 60 chars)",
           "seo_description": "Meta description (under 160 chars)",
           "tags": ["tag1", "tag2", "tag3"]
         }
    `;

    const dataSources: AIDataSource[] = [
        { 
            source_type: sourceUrl ? 'scraped' : 'official_site', 
            source_name: sourceUrl ? 'Web Source' : 'InvestingPro Knowledge Base',
            source_url: sourceUrl,
            last_verified: new Date().toISOString(),
            confidence: sourceUrl ? 0.8 : 1.0 
        }
    ];

    try {
        const result = await api.integrations.Core.InvokeLLM({
            prompt,
            operation: 'generate_article',
            contextData: { topic, keywords },
            dataSources
        });

        if (!result) {
            throw new Error('LLM returned no result');
        }

        // Store usage and provider info in result for cost tracking (will be logged after article creation)
        // Usage info is already included in result from InvokeLLM

        // The Unified API (InvokeLLM) might have already parsed the JSON
        // If 'title' or 'excerpt' exist at the top level, it's already parsed
        if (result.title && result.content) {
            // Inject affiliate links before returning
            const contentWithLinks = await linkInjector.injectLinks(result.content || '');
            
            return {
                title: result.title || topic,
                content: contentWithLinks || '',
                excerpt: result.excerpt || '',
                seo_title: result.seo_title || result.title || topic,
                seo_description: result.seo_description || result.excerpt || '',
                tags: result.tags || [],
                provider: result.provider,
                model: result.model,
                usage: result.usage,
                ai_metadata: result.ai_metadata || {
                    data_sources: dataSources,
                    confidence: calculateConfidence(dataSources),
                    change_log: [createChangeLog('created', ['Article generated by AI'], 'ai')],
                    generated_at: new Date().toISOString(),
                    generated_by: 'ai',
                    requires_review: true,
                    review_status: 'pending',
                    forbidden_phrases_found: result.validation_warnings || [],
                    allowed_operations: ALLOWED_AI_OPERATIONS
                }
            };
        }

        // Fallback: If it's a string or missing fields, try to parse it manually
        // result.content is our primary source of text from InvokeLLM
        const rawText = result.content || '';
        
        try {
            // If the raw text looks like JSON, try to parse it
            if (rawText.trim().startsWith('{')) {
                let cleanContent = rawText.trim();
                if (cleanContent.startsWith('```')) {
                    cleanContent = cleanContent.replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
                }
                const parsed = JSON.parse(cleanContent);
                return {
                    title: parsed.title || topic,
                    content: parsed.content || '',
                    excerpt: parsed.excerpt || '',
                    seo_title: parsed.seo_title || parsed.title || topic,
                    seo_description: parsed.seo_description || parsed.excerpt || '',
                    tags: parsed.tags || [],
                    provider: result.provider,
                    model: result.model,
                    usage: result.usage,
                    ai_metadata: result.ai_metadata || {}
                };
            }
            
            // Otherwise, it's just raw markdown text
            throw new Error('Not a JSON response');
        } catch (parseError) {
            logger.warn('AI response was not JSON, returning as-is', { provider: result.provider });
            return {
                title: topic,
                content: rawText,
                excerpt: topic,
                seo_title: topic,
                seo_description: topic,
                tags: keywords,
                provider: result.provider,
                model: result.model,
                usage: result.usage,
                ai_metadata: result.ai_metadata || {}
            };
        }

    } catch (error) {
        logger.error('Article Generation Failed', error as Error);
        throw error;
    }
}
