"use client";

import React, { useState, useMemo } from "react";
import {
  IndianRupee,
  Calendar,
  Percent,
  TrendingUp,
  Briefcase,
  PiggyBank,
  Info,
} from "lucide-react";
import { SliderInput } from "./shared/SliderInput";
import { ResultCard } from "./shared/ResultCard";
import { AIInsight } from "./shared/AIInsight";
import { WhatIfScenarios } from "./shared/WhatIfScenarios";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  PieChart,
  Pie,
  Cell,
  formatINR,
  yAxisINR,
} from "./shared/charts";

export function EPFCalculator() {
  const [basicSalary, setBasicSalary] = useState(30000);
  const [currentAge, setCurrentAge] = useState(28);
  const [retirementAge, setRetirementAge] = useState(58);
  const [currentBalance, setCurrentBalance] = useState(200000);
  const [annualIncrement, setAnnualIncrement] = useState(5);
  const [epfRate, setEpfRate] = useState(8.25);

  const calcEPF = (
    basic: number,
    yearsToRet: number,
    existing: number,
    increment: number,
    rate: number,
  ) => {
    const monthlyRate = rate / 100 / 12;
    let balance = existing;
    let totalEmployee = 0,
      totalEmployer = 0,
      totalInterest = 0;
    let currentBasic = basic;
    const yearlyData = [];

    for (let year = 1; year <= yearsToRet; year++) {
      const empMonthly = currentBasic * 0.12;
      const erEPFMonthly = currentBasic * 0.0367;
      const totalMonthly = empMonthly + erEPFMonthly;
      let yearInterest = 0;

      for (let m = 1; m <= 12; m++) {
        balance += totalMonthly;
        const mi = balance * monthlyRate;
        balance += mi;
        yearInterest += mi;
      }

      totalEmployee += empMonthly * 12;
      totalEmployer += erEPFMonthly * 12;
      totalInterest += yearInterest;

      yearlyData.push({
        year: `Y${year}`,
        balance: Math.round(balance),
        contributions: Math.round(totalEmployee + totalEmployer + existing),
      });
      currentBasic *= 1 + increment / 100;
    }

    const pensionableSalary = Math.min(basic, 15000);
    const pensionableService = Math.min(yearsToRet, 35);
    const monthlyPension = Math.round(
      (pensionableSalary * pensionableService) / 70,
    );

    return {
      maturity: Math.round(balance),
      totalEmployee: Math.round(totalEmployee),
      totalEmployer: Math.round(totalEmployer),
      totalInterest: Math.round(totalInterest),
      yearlyData,
      monthlyPension,
      multiplier: balance / (totalEmployee + totalEmployer + existing),
    };
  };

  const yearsToRet = Math.max(retirementAge - currentAge, 1);
  const result = useMemo(
    () =>
      calcEPF(
        basicSalary,
        yearsToRet,
        currentBalance,
        annualIncrement,
        epfRate,
      ),
    [basicSalary, yearsToRet, currentBalance, annualIncrement, epfRate],
  );

  const scenarios = useMemo(() => {
    const low = calcEPF(basicSalary, yearsToRet, currentBalance, 3, epfRate);
    const mid = calcEPF(basicSalary, yearsToRet, currentBalance, 5, epfRate);
    const high = calcEPF(basicSalary, yearsToRet, currentBalance, 10, epfRate);
    return [
      {
        label: "3% Increment",
        description: "Slow growth career",
        value: formatINR(low.maturity),
        subtext: `Interest: ${formatINR(low.totalInterest)}`,
        type: "conservative" as const,
      },
      {
        label: "5% Increment",
        description: "Average career growth",
        value: formatINR(mid.maturity),
        subtext: `Interest: ${formatINR(mid.totalInterest)}`,
        type: "moderate" as const,
      },
      {
        label: "10% Increment",
        description: "Fast-track career",
        value: formatINR(high.maturity),
        subtext: `Interest: ${formatINR(high.totalInterest)}`,
        type: "aggressive" as const,
      },
    ];
  }, [basicSalary, yearsToRet, currentBalance, epfRate]);

  const insights = useMemo(() => {
    const ins: string[] = [];
    const totalContrib =
      result.totalEmployee + result.totalEmployer + currentBalance;
    ins.push(
      `Compounding contributes ${formatINR(result.totalInterest)} — that's ${((result.totalInterest / result.maturity) * 100).toFixed(0)}% of your corpus generated by interest alone.`,
    );
    ins.push(
      `Your employer adds ${formatINR(result.totalEmployer)} to your EPF (3.67% of basic). The remaining 8.33% goes to EPS pension.`,
    );
    if (yearsToRet >= 10) {
      const earlyRetire = calcEPF(
        basicSalary,
        yearsToRet - 5,
        currentBalance,
        annualIncrement,
        epfRate,
      );
      ins.push(
        `Retiring 5 years early reduces corpus by ${formatINR(result.maturity - earlyRetire.maturity)}. The last years matter most due to compounding.`,
      );
    }
    return ins;
  }, [result, yearsToRet, currentBalance, basicSalary, annualIncrement]);

  const pieData = [
    {
      name: "Your Contribution",
      value: result.totalEmployee,
      color: "#166534",
    },
    { name: "Employer EPF", value: result.totalEmployer, color: "#22c55e" },
    { name: "Interest Earned", value: result.totalInterest, color: "#86efac" },
    ...(currentBalance > 0
      ? [{ name: "Existing Balance", value: currentBalance, color: "#d97706" }]
      : []),
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white border border-ink/10 rounded-2xl p-6 shadow-sm">
          <h2 className="text-base font-display font-semibold text-ink mb-5">
            EPF Details
          </h2>
          <div className="space-y-5">
            <SliderInput
              label="Basic Salary (Monthly)"
              icon={IndianRupee}
              value={basicSalary}
              onChange={setBasicSalary}
              min={5000}
              max={300000}
              step={1000}
              formatDisplay={formatINR}
            />
            <div className="grid grid-cols-2 gap-4">
              <SliderInput
                label="Current Age"
                icon={Calendar}
                value={currentAge}
                onChange={setCurrentAge}
                min={18}
                max={55}
                step={1}
                suffix=" yrs"
              />
              <SliderInput
                label="Retirement Age"
                icon={Briefcase}
                value={retirementAge}
                onChange={setRetirementAge}
                min={45}
                max={65}
                step={1}
                suffix=" yrs"
              />
            </div>
            <SliderInput
              label="Current EPF Balance"
              icon={PiggyBank}
              value={currentBalance}
              onChange={setCurrentBalance}
              min={0}
              max={5000000}
              step={10000}
              formatDisplay={formatINR}
            />
            <SliderInput
              label="Annual Salary Increment"
              icon={TrendingUp}
              value={annualIncrement}
              onChange={setAnnualIncrement}
              min={0}
              max={20}
              step={0.5}
              suffix="%"
            />
            <SliderInput
              label="EPF Interest Rate"
              icon={Percent}
              value={epfRate}
              onChange={setEpfRate}
              min={6}
              max={12}
              step={0.05}
              suffix="% p.a."
            />
          </div>
          <div className="mt-4 bg-blue-50 border border-blue-200 rounded-lg p-3 text-xs text-blue-800">
            <Info size={14} className="inline mr-1" />
            <strong>FY 2024-25 Rate:</strong> EPFO declared 8.25%. Employee:
            12%, Employer: 12% (8.33% EPS + 3.67% EPF).
          </div>
        </div>

        <div className="space-y-4">
          <ResultCard
            title="EPF Corpus at Retirement"
            value={formatINR(result.maturity)}
            ratingLabel={`${result.multiplier.toFixed(1)}x wealth multiplier`}
            ratingType="positive"
            metrics={[
              {
                label: "Your Contribution",
                value: formatINR(result.totalEmployee),
              },
              { label: "Employer EPF", value: formatINR(result.totalEmployer) },
              {
                label: "Interest Earned",
                value: formatINR(result.totalInterest),
                highlight: true,
              },
              {
                label: "EPS Pension",
                value: `${formatINR(result.monthlyPension)}/mo`,
              },
            ]}
          />
          <AIInsight insights={insights} />
        </div>
      </div>

      <WhatIfScenarios scenarios={scenarios} />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-white border border-ink/10 rounded-2xl p-5 shadow-sm">
          <h3 className="text-sm font-display font-semibold text-ink mb-4">
            EPF Growth Over {yearsToRet} Years
          </h3>
          <div className="h-[280px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart
                data={result.yearlyData.filter(
                  (_, i) =>
                    i % (yearsToRet > 25 ? 5 : yearsToRet > 15 ? 3 : 1) === 0 ||
                    i === result.yearlyData.length - 1,
                )}
              >
                <defs>
                  <linearGradient id="epfGrowthV2" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#22c55e" stopOpacity={0.25} />
                    <stop offset="95%" stopColor="#22c55e" stopOpacity={0.02} />
                  </linearGradient>
                </defs>
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="#f1f5f9"
                  vertical={false}
                />
                <XAxis
                  dataKey="year"
                  fontSize={11}
                  tick={{ fill: "#94a3b8" }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  fontSize={11}
                  tick={{ fill: "#94a3b8" }}
                  axisLine={false}
                  tickLine={false}
                  tickFormatter={yAxisINR}
                />
                <Tooltip
                  formatter={(value: any) => [formatINR(Number(value)), ""]}
                  contentStyle={{ borderRadius: "10px", fontSize: "12px" }}
                />
                <Area
                  type="monotone"
                  dataKey="contributions"
                  stroke="#166534"
                  strokeWidth={1.5}
                  strokeDasharray="6 4"
                  fill="none"
                  name="Contributions"
                />
                <Area
                  type="monotone"
                  dataKey="balance"
                  stroke="#22c55e"
                  strokeWidth={2.5}
                  fill="url(#epfGrowthV2)"
                  name="Total Balance"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white border border-ink/10 rounded-2xl p-5 shadow-sm">
          <h3 className="text-sm font-display font-semibold text-ink mb-3">
            Corpus Breakdown
          </h3>
          <div className="h-[200px]">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={55}
                  outerRadius={80}
                  dataKey="value"
                  stroke="none"
                  startAngle={90}
                  endAngle={-270}
                >
                  {pieData.map((entry, i) => (
                    <Cell key={i} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip
                  formatter={(value: any) => formatINR(Number(value))}
                  contentStyle={{ borderRadius: "10px", fontSize: "12px" }}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="flex flex-wrap justify-center gap-3 mt-1">
            {pieData.map((d) => (
              <div
                key={d.name}
                className="flex items-center gap-1.5 text-[10px]"
              >
                <div
                  className="w-2 h-2 rounded-full"
                  style={{ backgroundColor: d.color }}
                />
                <span className="text-ink-60">{d.name}</span>
              </div>
            ))}
          </div>

          {/* Monthly breakdown */}
          <div className="mt-4 pt-4 border-t border-ink/5 space-y-2 text-xs">
            <p className="font-semibold text-ink">Monthly Breakdown</p>
            <div className="flex justify-between">
              <span className="text-ink-60">Employee (12%)</span>
              <span className="font-semibold">
                {formatINR(basicSalary * 0.12)}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-ink-60">Employer EPF (3.67%)</span>
              <span className="font-semibold">
                {formatINR(basicSalary * 0.0367)}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-ink-60">Employer EPS (8.33%)</span>
              <span className="font-semibold text-indian-gold">
                {formatINR(basicSalary * 0.0833)}
              </span>
            </div>
            <div className="flex justify-between pt-2 border-t border-ink/5 font-bold text-authority-green">
              <span>Total to EPF/mo</span>
              <span>{formatINR(basicSalary * 0.1567)}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
